server:
  port: 9090 # 端口

spring:
  application:
    name: order-service # 应用名称

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/

# 自定义配置
name: order-service-dev-2.0
password: '{cipher}c25e868237dcb0d0cbad9072c86f81b23628db2e2cb5f66e0f32c3e6408bfb91'  #对{cipher}开头的数据进行解密(config-server对称加密)
