server:
  port: 9090

spring:
  application:
    name: order-service

# 配置 eureka server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true   #是否将自己注册到注册中心，默认为true
    register-fetch-interval-seconds: 10 #表示eureka client 间隔多久去服务器拉去注册信息，默认为30秒
    service-url:                  #设置服务注册中心地址
      defaultZone: http://root:123456@localhost:8761/eureka/, http://root:123456@localhost:8762/eureka/


feign:
  hystrix:
    enabled: true   #开启 hystrix 支持
  httpclient:
    enabled: true   #开启 httpclient

#度量指标监控与健康检查(hystrix)
# management:
#   endpoints:
#     web:
#       exposure:
#         include: hystrix.stream


#度量指标监控与监控检查(refresh)
management:
  endpoints:
    web:
      base-path: /actuator  #访问端点根路径，默认/actuator
      exposure:
        include:
          - '*'         #需要开启的端点，这里主要用到的是 refresh 这个端点
#        exclude:       #不需要开启的端点
#          -

# 自定义配置
name: order-service-default-1.0
